# Generated by Django 3.2.25 on 2024-05-30 10:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240530_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
